trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # Deploy Logic App
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental
        deploymentOutputs: logicAppOutputs

    # Wait for endpoint readiness
    - script: sleep 30
      displayName: Wait for Logic App

    # Capture callback URL (WITH sig)
    - script: |
        echo "##vso[task.setvariable variable=logicAppCallbackUrl]$(logicAppOutputs.callbackUrl.value)"
      displayName: Set callback URL

    # Create Event Grid subscription
    - task: AzureCLI@2
      displayName: Create Event Grid subscription
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az eventgrid event-subscription create \
            --name iscala-archive-egsub \
            --source-resource-id /subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/rg-iscala-archive/providers/Microsoft.Storage/storageAccounts/snapshottestsa \
            --endpoint "$(logicAppCallbackUrl)" \
            --included-event-types Microsoft.Storage.BlobCreated Microsoft.Storage.BlobTierChanged
