trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'   # Your Azure RM service connection
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: DeployDev
  displayName: Deploy Development Environment
  jobs:
  - job: Deploy
    displayName: Deploy Logic App Solution
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # ------------------------
    # 1️⃣ Deploy API Connections
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: infra/connections.json
        csmParametersFile: infra/parameters/connections.dev.json
        deploymentMode: Incremental

    # ------------------------
    # 2️⃣ Deploy Logic App
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.d

