trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: Dev
  displayName: Deploy Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # 1️⃣ Deploy Logic App
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental
        deploymentOutputs: logicAppOutputs

    # 2️⃣ Wait for Logic App readiness
    - script: |
        echo "Waiting 30 seconds for Logic App endpoint to become available..."
        sleep 30
      displayName: Wait for Logic App readiness

    # 3️⃣ Capture Logic App callback URL
    - script: |
        echo "Logic App callback URL:"
        echo "$(logicAppOutputs.callbackUrl.value)"
        echo "##vso[task.setvariable variable=logicAppCallbackUrl]$(logicAppOutputs.callbackUrl.value)"
      displayName: Set pipeline variable for Event Grid

    # 4️⃣ Deploy Event Grid subscription via Azure CLI
    - task: AzureCLI@2
      displayName: Deploy Event Grid Subscription
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az eventgrid event-subscription create \
            --name iscala-archive-egsub \
            --source-resource-id /subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/rg-iscala-archive/providers/Microsoft.Storage/storageAccounts/snapshottestsa \
            --endpoint "$(logicAppCallbackUrl)" \
            --included-event-types Microsoft.Storage.BlobCreated Microsoft.Storage.BlobTierChanged \
            --max-delivery-attempts 5 \
            --event-ttl 1440
