trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: DeployDev
  displayName: Deploy Development Environment
  jobs:
  - job: Deploy
    displayName: Deploy Logic App Solution
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # ------------------------
    # 1️⃣ Deploy API Connections
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: infra/connections.json
        csmParametersFile: infra/parameters/connections.dev.json
        deploymentMode: Incremental

    # ------------------------
    # 2️⃣ Deploy Logic App
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental

    # ------------------------
    # 3️⃣ Fetch Logic App Callback URL
    # ------------------------
    - task: AzureCLI@2
      displayName: Get Logic App Callback URL
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          CALLBACK_URL=$(az logic workflow show \
            --resource-group $(resourceGroupName) \
            --name la-iscala-archive \
            --query "properties.accessEndpoint" -o tsv)
          echo "##vso[task.setvariable variable=logicAppCallbackUrl]$CALLBACK_URL"

    # ------------------------
    # 4️⃣ Deploy Event Grid Subscription
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Event Grid
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: infra/eventgrid.json
        csmParametersFile: infra/parameters/eventgrid.dev.json
        overrideParameters: >
          logicAppCallbackUrl=$(logicAppCallbackUrl)
        deploymentMode: Incremental
