trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # Deploy Logic App
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/dev.json
        deploymentOutputs: logicAppOutputs

    # SHOW THE CALLBACK URL
    - script: |
        echo "============================"
        echo "LOGIC APP CALLBACK URL:"
        echo "$(logicAppOutputs.callbackUrl.value)"
        echo "============================"
      displayName: SHOW callback URL

    # Deploy Event Grid
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Event Grid
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: infra/eventgrid.json
        overrideParameters: >
          -eventSubscriptionName iscala-archive-egsub
          -storageAccountResourceId /subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/snapshottest-rg/providers/Microsoft.Storage/storageAccounts/snapshottestsa
          -logicAppCallbackUrl "$(logicAppOutputs.callbackUrl.value)"


