trigger:
- main

variables:
- group: variable_iScalaArchive

- name: azureServiceConnection
  value: 'Azure-Service-Connection'

- name: functionAppName
  value: 'fa-iscala-eg-proxy-dev'

- name: workbookName
  value: 'wb-iscala-forwarding'

- name: eventSubscriptionName
  value: 'iscala-archive-egsub'

- name: appInsightsName
  value: 'fa-iscala-eg-proxy-dev'

- name: storageAccountResourceId
  value: "/subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/$(resourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(storageAccount)"

stages:
- stage: Dev
  displayName: Deploy Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    - bash: |
        python3 -m json.tool infra/functionapp.json > /dev/null
        python3 -m json.tool logicapp/logicapp.json > /dev/null
        python3 -m json.tool infra/connections.json > /dev/null
      displayName: Validate templates (JSON)

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/connections.json
        csmParametersFile: infra/parameters/connections.dev.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Function infra
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/functionapp.json
        csmParametersFile: infra/parameters/functionapp.dev.json
        # overrideParameters: >
        #   -logicAppCallbackUrl "$(logicAppCallbackUrl)"
        #   -functionAppName "$(functionAppName)"
        #   -location "$(rgLocation)"
        #   -storageAccountName "$(storageAccount)"
        deploymentMode: Incremental
        deploymentOutputs: functionOutputs

    - script: |
        echo "##vso[task.setvariable variable=functionWebhookUrl]$(functionOutputs.functionWebhookUrl.value)"
      displayName: Set Function webhook URL

    - task: ArchiveFiles@2
      displayName: Zip Function code
      inputs:
        rootFolderOrFile: functionapp
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/functionapp.zip
        replaceExistingArchive: true

    - task: AzureFunctionApp@2
      displayName: Deploy Function package
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: functionApp
        appName: $(functionAppName)
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'

    - task: AzureCLI@2
      displayName: Set subscriptionId variable
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          SUB="$(az account show --query id -o tsv)"
          echo "##vso[task.setvariable variable=subscriptionId]$SUB"

    # Deploy Action Group (email)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Alert Action Group (email)
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/alerts-actiongroup.json
        overrideParameters: >
          -actionGroupName "ag-iscala-archive-sev2"
          -emailAddress "mats.johannesson@easec.se"
        deploymentMode: Incremental
        deploymentOutputs: agOutputs

   # Deploy Log Alert (Sev2)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Alert Rule (forwarding failures) Sev2
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/alerts-forwardingfail.json
        csmParametersFile: infra/parameters/alerts-forwardingfail.dev.json
        deploymentMode: Incremental


    - task: AzureCLI@2
      displayName: Pre-flight check (Function + Forwarding)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -euo pipefail

          FUNC_URL="$(functionWebhookUrl)"
          echo "Function endpoint: $FUNC_URL"

          echo "== 1) Validate Function endpoint =="
          resp="$(curl -sS -i -X POST "$FUNC_URL" -H "Content-Type: application/json" \
            -d '[{"eventType":"Microsoft.EventGrid.SubscriptionValidationEvent","data":{"validationCode":"abc123"}}]')"
          echo "$resp" | grep -q "HTTP/1.1 200"
          echo "$resp" | grep -q '"validationResponse"'

          echo "== 2) Blob Hot event test =="
          payload='[{"topic":"'"$(storageAccountResourceId)"'","subject":"/blobServices/default/containers/snapshot/blobs/devops-preflight.txt","eventType":"Microsoft.Storage.BlobTierChanged","id":"preflight","data":{"accessTier":"Hot","previousTier":"Cool","url":"https://'"$(storageAccount)"'.blob.core.windows.net/snapshot/devops-preflight.txt"}}]'

          resp2="$(curl -sS -X POST "$FUNC_URL" -H "Content-Type: application/json" -d "$payload")"

          echo "== Blob test response body =="
          echo "$resp2"

          ok="$(printf '%s' "$resp2" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(str(d.get("ok", False)).lower())' 2>/dev/null || echo false)"

          if [ "$ok" != "true" ]; then
            echo "ERROR: Missing ok=true"
            echo "$resp2"
            exit 1
          fi

          echo "OK: Pre-flight passed."


    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Workbook (forwarding panel)
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/workbook-forwarding.json
        csmParametersFile: infra/parameters/workbook-forwarding.dev.json
        overrideParameters: >
          -location "$(rgLocation)"
          -workbookName "7f3e2f8a-9d8a-4e5e-b5b8-3a4b9b8f7d21"
          -appInsightsResourceId "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Insights/components/$(appInsightsName)"
        deploymentMode: Incremental



    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Portal Dashboard (pins Workbook)
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/portal-dashboard.json
        csmParametersFile: infra/parameters/portal-dashboard.dev.json
        deploymentMode: Incremental
  
    - task: AzureCLI@2
      displayName: Verify dashboard exists
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az resource show \
            --resource-group rg-iscala-archive \
            --resource-type Microsoft.Portal/dashboards \
            --name db-iscala-forwarding \
            --query "{name:name, location:location, id:id}" -o json

    - task: AzureCLI@2
      displayName: Create Event Grid subscription
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          az eventgrid event-subscription delete --name "$(eventSubscriptionName)" --source-resource-id "$(storageAccountResourceId)" || true

          az eventgrid event-subscription create \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" \
            --endpoint "$(functionWebhookUrl)" \
            --included-event-types Microsoft.Storage.BlobCreated Microsoft.Storage.BlobTierChanged
