trigger:
- main

variables:
- group: variable_iScaleArchive

- name: azureServiceConnection
  value: 'Azure-Service-Connection'

- name: storageAccountResourceId
  value: "/subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/$(resourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(storageAccount)"

- name: eventSubscriptionName
  value: "iscala-archive-egsub"

stages:
- stage: Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # 1) Deploy Connections (must be before Logic App)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/connections.json
        csmParametersFile: infra/parameters/connections.dev.json
        deploymentMode: Incremental

    # 2) Deploy Logic App (after connections)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental

    # 3) Deploy Function infra (ARM) with secret callback URL
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Function App infra
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/functionapp.json
        csmParametersFile: infra/parameters/functionapp.dev.json
        overrideParameters: >
          -logicAppCallbackUrl "$(logicAppCallbackUrl)"
          -functionAppName "fa-iscala-eg-proxy-dev"
          -location "$(rgLocation)"
          -storageAccountName "$(storageAccount)"
        deploymentMode: Incremental
        deploymentOutputs: functionOutputs

    # 4) Capture function webhook url
    - script: |
        echo "Function webhook URL: $(functionOutputs.functionWebhookUrl.value)"
        echo "##vso[task.setvariable variable=functionWebhookUrl]$(functionOutputs.functionWebhookUrl.value)"
      displayName: Set Function webhook URL

    # 5) Zip and deploy function code
    - task: ArchiveFiles@2
      displayName: Zip Function App
      inputs:
        rootFolderOrFile: functionapp
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/functionapp.zip
        replaceExistingArchive: true

    - bash: |
        echo "Listing contents of functionapp.zip"
        python3 - << 'PY'
        import zipfile
        zip_path = "$(Build.ArtifactStagingDirectory)/functionapp.zip"
        z = zipfile.ZipFile(zip_path)
        for name in z.namelist():
            print(name)
        PY
      displayName: Inspect function zip contents

    - task: AzureFunctionApp@2
      displayName: Deploy Function App package
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: functionApp
        appName: 'fa-iscala-eg-proxy-dev'
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'

    - task: AzureCLI@2
      displayName: Pre-flight test Function endpoint (Event Grid validation)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          echo "Testing Function endpoint: $(functionWebhookUrl)"

          resp="$(curl -sS -i -X POST "$(functionWebhookUrl)" \
            -H "Content-Type: application/json" \
            -d '[{"eventType":"Microsoft.EventGrid.SubscriptionValidationEvent","data":{"validationCode":"abc123"}}]')"

          echo "$resp"

          # Must return HTTP 200 and include validationResponse
          echo "$resp" | grep -q "HTTP/1.1 200" || (echo "ERROR: Function did not return HTTP 200" && exit 1)
          echo "$resp" | grep -q '"validationResponse"' || (echo 'ERROR: Missing "validationResponse" in body' && exit 1)

          echo "OK: Function endpoint validates correctly."

    - task: AzureCLI@2
      displayName: Pre-flight test Function endpoint (Blob event path)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          echo "Testing Function endpoint (BlobTierChanged payload): $(functionWebhookUrl)"

          payload='[
            {
              "topic": "$(storageAccountResourceId)",
              "subject": "/blobServices/default/containers/snapshot/blobs/devops-preflight.txt",
              "eventType": "Microsoft.Storage.BlobTierChanged",
              "id": "preflight-1",
              "data": {
                "accessTier": "Hot",
                "previousTier": "Cool",
                "url": "https://$(storageAccount).blob.core.windows.net/snapshot/devops-preflight.txt"
              },
              "metadataVersion": "1",
              "eventTime": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
            }
          ]'

          resp="$(curl -sS -i -X POST "$(functionWebhookUrl)" \
            -H "Content-Type: application/json" \
            -d "$payload")"

          echo "$resp"

          # Must return HTTP 200 and include "ok": true
          echo "$resp" | grep -q "HTTP/1.1 200" || (echo "ERROR: Function did not return HTTP 200" && exit 1)
          echo "$resp" | grep -q '"ok"[[:space:]]*:[[:space:]]*true' || (echo 'ERROR: Missing `"ok": true` in body' && exit 1)

          echo "OK: Function blob event path works."


    # 6) Recreate Event Grid subscription (always last)
    - task: AzureCLI@2
      displayName: Create Event Grid subscription (to Function)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          echo "Using endpoint: $(functionWebhookUrl)"
          echo "Storage scope: $(storageAccountResourceId)"

          az eventgrid event-subscription delete \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" || true

          az eventgrid event-subscription create \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" \
            --endpoint "$(functionWebhookUrl)" \
            --included-event-types Microsoft.Storage.BlobCreated Microsoft.Storage.BlobTierChanged

          az eventgrid event-subscription show \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" \
            --query "destination.endpointBaseUrl" -o tsv

