trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: DeployDev
  displayName: Deploy Development Environment
  jobs:
  - job: Deploy
    displayName: Deploy Logic App Solution
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # ------------------------
    # 🔍 Debug: Verify template files exist
    # ------------------------
    - script: |
        echo "Checking template files..."
        files=(
          "$(Build.SourcesDirectory)/infra/connections.json"
          "$(Build.SourcesDirectory)/infra/parameters/connections.dev.json"
          "$(Build.SourcesDirectory)/logicapp/logicapp.json"
          "$(Build.SourcesDirectory)/infra/parameters/logicapp.dev.json"
          "$(Build.SourcesDirectory)/infra/eventgrid.json"
          "$(Build.SourcesDirectory)/infra/parameters/eventgrid.dev.json"
        )
        missing=false
        for f in "${files[@]}"; do
          if [ ! -f "$f" ]; then
            echo "❌ File not found: $f"
            missing=true
          else
            echo "✅ Found: $f"
          fi
        done
        if [ "$missing" = true ]; then
          echo "Some template files are missing! Aborting pipeline."
          exit 1
        fi
      displayName: "Verify template and parameter files exist"

    # ------------------------
    # 1️⃣ Deploy API Connections
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/infra/connections.json'
        csmParametersFile: '$(Build.SourcesDirectory)/infra/parameters/connections.dev.json'
        deploymentMode: Incremental

    # ------------------------
    # 2️⃣ Deploy Logic App
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/logicapp/logicapp.json'
        csmParametersFile: '$(Build.SourcesDirectory)/infra/parameters/logicapp.dev.json'
        deploymentMode: Incremental

    # ------------------------
    # 3️⃣ Fetch Logic App Callback URL
    # ------------------------
    - task: AzureCLI@2
      displayName: Get Logic App Callback URL
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Fetching Logic App callback URL..."
          CALLBACK_URL=$(az logic workflow show \
            --resource-group $(resourceGroupName) \
            --name la-iscala-archive \
            --query "properties.accessEndpoint" -o tsv)
          echo "Logic App callback URL: $CALLBACK_URL"
          echo "##vso[task.setvariable variable=logicAppCallbackUrl]$CALLBACK_URL"

    # ------------------------
    # 4️⃣ Deploy Event Grid
    # ------------------------
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Event Grid
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/infra/eventgrid.json'
        csmParametersFile: '$(Build.SourcesDirectory)/infra/parameters/eventgrid.dev.json'
        overrideParameters: '-logicAppCallbackUrl "$(logicAppCallbackUrl)"'
        deploymentMode: Incremental
