trigger:
- main

variables:
  azureServiceConnection: 'Azure-Service-Connection'
  resourceGroupName: 'rg-iscala-archive'
  location: 'swedencentral'

stages:
- stage: Dev
  displayName: Deploy Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # 1️⃣ Deploy Logic App
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental
        deploymentOutputs: logicAppOutputs

    # 2️⃣ Capture Logic App callback URL
    - script: |
        echo "Logic App callback URL:"
        echo "$(logicAppOutputs.callbackUrl.value)"
        echo "##vso[task.setvariable variable=logicAppCallbackUrl]$(logicAppOutputs.callbackUrl.value)"
      displayName: Set pipeline variable for Event Grid

    # 3️⃣ Deploy Event Grid subscription
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Event Grid
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: infra/eventgrid.json
        deploymentMode: Incremental
        overrideParameters: >
          -eventSubscriptionName iscala-archive-egsub
          -storageAccountResourceId /subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/rg-iscala-archive/providers/Microsoft.Storage/storageAccounts/snapshottestsa
          -logicAppCallbackUrl "$(logicAppCallbackUrl)"

