trigger:
- main

variables:
- group: variable_iScaleArchive

- name: azureServiceConnection
  value: 'Azure-Service-Connection'

- name: functionAppName
  value: 'fa-iscala-eg-proxy-dev'

- name: appInsightsName
  value: 'fa-iscala-eg-proxy-dev-appi'

- name: eventSubscriptionName
  value: 'iscala-archive-egsub'

- name: storageAccountResourceId
  value: "/subscriptions/0ac447d7-fbc3-4d3d-84d4-37bb9a71e089/resourceGroups/$(resourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(storageAccount)"

stages:
- stage: Dev
  displayName: Deploy Dev
  jobs:
  - job: Deploy
    pool:
      name: easec-pool
    steps:
    - checkout: self

    # 1) Deploy Connections (must be before Logic App)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Connections
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/connections.json
        csmParametersFile: infra/parameters/connections.dev.json
        deploymentMode: Incremental

    # 2) Deploy Logic App (after connections)
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Logic App
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: logicapp/logicapp.json
        csmParametersFile: infra/parameters/logicapp.dev.json
        deploymentMode: Incremental

    # 3) Deploy Function infra (ARM) with secret callback URL
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Function App infra
      inputs:
        azureResourceManagerConnection: $(azureServiceConnection)
        deploymentScope: Resource Group
        resourceGroupName: $(resourceGroupName)
        location: $(rgLocation)
        csmFile: infra/functionapp.json
        csmParametersFile: infra/parameters/functionapp.dev.json
        overrideParameters: >
          -logicAppCallbackUrl "$(logicAppCallbackUrl)"
          -functionAppName "$(functionAppName)"
          -location "$(rgLocation)"
          -storageAccountName "$(storageAccount)"
        deploymentMode: Incremental
        deploymentOutputs: functionOutputs

    # 4) Capture function webhook url
    - script: |
        echo "Function webhook URL: $(functionOutputs.functionWebhookUrl.value)"
        echo "##vso[task.setvariable variable=functionWebhookUrl]$(functionOutputs.functionWebhookUrl.value)"
      displayName: Set Function webhook URL

    # 5) Zip and deploy function code
    - task: ArchiveFiles@2
      displayName: Zip Function App
      inputs:
        rootFolderOrFile: functionapp
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/functionapp.zip
        replaceExistingArchive: true

    - bash: |
        echo "Listing contents of functionapp.zip"
        python3 - << 'PY'
        import zipfile
        zip_path = "$(Build.ArtifactStagingDirectory)/functionapp.zip"
        z = zipfile.ZipFile(zip_path)
        for name in z.namelist():
            print(name)
        PY
      displayName: Inspect function zip contents

    - task: AzureFunctionApp@2
      displayName: Deploy Function App package
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: functionApp
        appName: $(functionAppName)
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'

    # 6) Pre-flight end-to-end checks (Function + Forwarding + AppInsights)
    - task: AzureCLI@2
      displayName: Pre-flight end-to-end check (Function + Forwarding + AppInsights)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          FUNC_URL="$(functionWebhookUrl)"
          APPINSIGHTS_NAME="$(appInsightsName)"
          RG="$(resourceGroupName)"

          echo "Function endpoint: $FUNC_URL"
          echo "App Insights: $APPINSIGHTS_NAME (RG: $RG)"

          echo "== 1) Validate Function endpoint (Event Grid validation event) =="
          resp="$(curl -sS -i -X POST "$FUNC_URL" \
            -H "Content-Type: application/json" \
            -d '[{"eventType":"Microsoft.EventGrid.SubscriptionValidationEvent","data":{"validationCode":"abc123"}}]')"
          echo "$resp"
          echo "$resp" | grep -q "HTTP/1.1 200" || (echo "ERROR: Validation test did not return HTTP 200" && exit 1)
          echo "$resp" | grep -q '"validationResponse"' || (echo 'ERROR: Validation test missing "validationResponse"' && exit 1)

          echo "== 2) Test blob event path (expects ok=true) =="
          payload='[
            {
              "topic": "'"$(storageAccountResourceId)"'",
              "subject": "/blobServices/default/containers/snapshot/blobs/devops-preflight.txt",
              "eventType": "Microsoft.Storage.BlobTierChanged",
              "id": "preflight-1",
              "data": {
                "accessTier": "Hot",
                "previousTier": "Cool",
                "url": "https://'"$(storageAccount)"'.blob.core.windows.net/snapshot/devops-preflight.txt"
              },
              "metadataVersion": "1",
              "eventTime": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
            }
          ]'

          resp2="$(curl -sS -i -X POST "$FUNC_URL" \
            -H "Content-Type: application/json" \
            -d "$payload")"
          echo "$resp2"
          echo "$resp2" | grep -q "HTTP/1.1 200" || (echo "ERROR: Blob test did not return HTTP 200" && exit 1)
          echo "$resp2" | grep -q '"ok"[[:space:]]*:[[:space:]]*true' || (echo 'ERROR: Blob test missing `"ok": true`' && exit 1)

          echo "== 3) Verify forwarding via Application Insights (200/202) =="
          COUNT="$(az monitor app-insights query \
            --app "$APPINSIGHTS_NAME" \
            --resource-group "$RG" \
            --analytics-query "traces
              | where timestamp > ago(15m)
              | where message contains \"Forwarded to Logic App. Status: 200\"
                 or message contains \"Forwarded to Logic App. Status: 202\"
              | count" \
            --query "tables[0].rows[0][0]" -o tsv)"

          echo "Forward-success count (last 15m): $COUNT"

          if [ "$COUNT" -lt 1 ]; then
            echo "ERROR: No successful forward logs (200/202) found in last 15 minutes."
            echo "Latest forward logs (any status):"
            az monitor app-insights query \
              --app "$APPINSIGHTS_NAME" \
              --resource-group "$RG" \
              --analytics-query "traces
                | where timestamp > ago(30m)
                | where message contains \"Forwarded to Logic App. Status\"
                | order by timestamp desc
                | take 10" \
              -o jsonc
            exit 1
          fi

          echo "OK: End-to-end pre-flight checks passed."

    # 7) Recreate Event Grid subscription (always last)
    - task: AzureCLI@2
      displayName: Create Event Grid subscription (to Function)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          echo "Using endpoint: $(functionWebhookUrl)"
          echo "Storage scope: $(storageAccountResourceId)"

          az eventgrid event-subscription delete \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" || true

          az eventgrid event-subscription create \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" \
            --endpoint "$(functionWebhookUrl)" \
            --included-event-types Microsoft.Storage.BlobCreated Microsoft.Storage.BlobTierChanged

          az eventgrid event-subscription show \
            --name "$(eventSubscriptionName)" \
            --source-resource-id "$(storageAccountResourceId)" \
            --query "destination.endpointBaseUrl" -o tsv
